# Generated by Django 5.0.6 on 2024-12-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Uav',
            fields=[
                ('uav_id', models.AutoField(primary_key=True, serialize=False)),
                ('uav_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartProduction',
            fields=[
                ('part_production_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.team'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.team')),
            ],
        ),
        migrations.CreateModel(
            name='UavParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.part')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.uav')),
            ],
        ),
        migrations.CreateModel(
            name='UavProduction',
            fields=[
                ('uav_production_id', models.AutoField(primary_key=True, serialize=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.part')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.uav')),
            ],
        ),
    ]
