# Generated by Django 5.0.6 on 2024-12-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0002_employee_employee_sicil_no_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
