# Generated by Django 5.0.6 on 2024-12-11 11:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0004_employee_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='partproduction',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='partproduction',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='partproduction',
            name='material_type',
            field=models.CharField(choices=[('ALUMINUM', 'Alüminyum'), ('COMPOSITE', 'Kompozit Malzeme'), ('TITANIUM', 'Titanyum'), ('PLASTIC', 'Plastik (Polymer)'), ('KEVLAR', 'Kevlar'), ('CERAMIC', 'Seramik')], default='ALUMINUM', max_length=100),
        ),
        migrations.AddField(
            model_name='partproduction',
            name='production_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partproduction',
            name='production_type',
            field=models.CharField(choices=[('MACHINE', 'Makine Üretimi'), ('CASTING', 'Döküm'), ('3D_PRINTING', '3D Baskı'), ('OTHER', 'Diğer')], default='MACHINE', max_length=20),
        ),
        migrations.AddField(
            model_name='partproduction',
            name='uav',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.uav'),
        ),
        migrations.AddField(
            model_name='partproduction',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='partproduction',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
