# Generated by Django 5.0.6 on 2024-12-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0005_partproduction_height_partproduction_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partproduction',
            name='production_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('assembly_id', models.AutoField(primary_key=True, serialize=False)),
                ('assembly_code', models.CharField(max_length=50, unique=True)),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.uav')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyPart',
            fields=[
                ('assembly_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.assembly')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.part')),
            ],
        ),
        migrations.DeleteModel(
            name='UavProduction',
        ),
    ]
