# Generated by Django 5.0.6 on 2024-12-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0007_remove_assemblypart_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UavProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_time', models.DateTimeField()),
                ('part_count', models.IntegerField(default=0)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoAPI.assembly')),
            ],
        ),
    ]
